export const BUSINESS = {
  name: "Rénovation BT",
  legalName: "Rénovation BT",
  tagline: "Rénovation et Entretien",
  slogan: "Votre artisan couvreur de confiance dans le Grand Est",
  phone: "07 61 54 53 43",
  phoneHref: "tel:+33761545343",
  phoneInternational: "+33761545343",
  email: "contact@artisan-boisson-teddy.fr",
  website: "https://artisan-boisson-teddy.fr",
  address: {
    street: "",
    city: "Écury-sur-Coole",
    postalCode: "51240",
    region: "Grand Est",
    country: "FR",
  },
  geo: {
    latitude: 48.8967,
    longitude: 4.2822,
  },
  hours: "Ouvert 24h/24 et 7j/7",
  experience: "+10 ans",
  googleRating: 5,
  googleReviewCount: 23,
  googleMapsUrl: "https://g.page/renovation-bt",
  hasMap: "https://www.google.com/maps/place/Écury-sur-Coole",
  serviceRadius: {
    value: 150,
    unit: "KMT",
  },
  sameAs: [
    "https://facebook.com/renovationbt",
    "https://instagram.com/renovationbt",
    "https://g.page/renovation-bt",
  ],
  social: {
    facebook: "https://facebook.com/renovationbt",
    instagram: "https://instagram.com/renovationbt",
    google: "https://g.page/renovation-bt",
  },
  departments: [
    "Marne (51)",
    "Aube (10)",
    "Haute-Marne (52)",
    "Meuse (55)",
    "Ardennes (08)",
    "Bas-Rhin (67)",
    "Haut-Rhin (68)",
    "Moselle (57)",
    "Meurthe-et-Moselle (54)",
    "Vosges (88)",
    "Aisne (02)",
  ],
  knowsAbout: [
    "couverture",
    "toiture",
    "zinguerie",
    "ravalement de façade",
    "gouttières",
    "démoussage",
    "nettoyage hydrofuge",
    "charpente",
    "isolation toiture",
    "étanchéité",
  ],
} as const;

export const SEO = {
  defaultTitle: "Couvreur Châlons-en-Champagne | Rénovation BT",
  titleTemplate: "%s | Rénovation BT",
  defaultDescription:
    "Couvreur à Châlons-en-Champagne (51). Artisan couvreur pour toiture, zinguerie, démoussage. Devis gratuit sous 24h. Intervention rapide en Marne.",
  ogImage: "/og-image.jpg",
  siteUrl: "https://www.renovationbt-chalons.fr",
} as const;
